//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.7.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Grammar\SeagullLexer.g4 by ANTLR 4.7.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.7.2")]
[System.CLSCompliant(false)]
public partial class SeagullLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		L_BRACKET=1, R_BRACKET=2, ID=3, INT_CONSTANT=4, REAL_CONSTANT=5, CHAR_CONSTANT=6, 
		SL_COMMENT=7, ML_COMMENT=8, BLANKS=9;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"DIGIT", "LETTER", "REAL", "TAG", "NL", "L_BRACKET", "R_BRACKET", "ID", 
		"INT_CONSTANT", "REAL_CONSTANT", "CHAR_CONSTANT", "SL_COMMENT", "ML_COMMENT", 
		"BLANKS"
	};


	public SeagullLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public SeagullLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'['", "']'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "L_BRACKET", "R_BRACKET", "ID", "INT_CONSTANT", "REAL_CONSTANT", 
		"CHAR_CONSTANT", "SL_COMMENT", "ML_COMMENT", "BLANKS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "SeagullLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override string SerializedAtn { get { return new string(_serializedATN); } }

	static SeagullLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static char[] _serializedATN = {
		'\x3', '\x608B', '\xA72A', '\x8133', '\xB9ED', '\x417C', '\x3BE7', '\x7786', 
		'\x5964', '\x2', '\v', '\xB7', '\b', '\x1', '\x4', '\x2', '\t', '\x2', 
		'\x4', '\x3', '\t', '\x3', '\x4', '\x4', '\t', '\x4', '\x4', '\x5', '\t', 
		'\x5', '\x4', '\x6', '\t', '\x6', '\x4', '\a', '\t', '\a', '\x4', '\b', 
		'\t', '\b', '\x4', '\t', '\t', '\t', '\x4', '\n', '\t', '\n', '\x4', '\v', 
		'\t', '\v', '\x4', '\f', '\t', '\f', '\x4', '\r', '\t', '\r', '\x4', '\xE', 
		'\t', '\xE', '\x4', '\xF', '\t', '\xF', '\x3', '\x2', '\x3', '\x2', '\x3', 
		'\x3', '\x3', '\x3', '\x3', '\x4', '\x5', '\x4', '%', '\n', '\x4', '\x3', 
		'\x4', '\x3', '\x4', '\x6', '\x4', ')', '\n', '\x4', '\r', '\x4', '\xE', 
		'\x4', '*', '\x3', '\x4', '\x3', '\x4', '\x3', '\x4', '\a', '\x4', '\x30', 
		'\n', '\x4', '\f', '\x4', '\xE', '\x4', '\x33', '\v', '\x4', '\x5', '\x4', 
		'\x35', '\n', '\x4', '\x3', '\x5', '\x3', '\x5', '\x3', '\x6', '\x3', 
		'\x6', '\x3', '\x6', '\x5', '\x6', '<', '\n', '\x6', '\x3', '\a', '\x3', 
		'\a', '\x3', '\b', '\x3', '\b', '\x3', '\t', '\x3', '\t', '\x5', '\t', 
		'\x44', '\n', '\t', '\x3', '\t', '\x3', '\t', '\x3', '\t', '\a', '\t', 
		'I', '\n', '\t', '\f', '\t', '\xE', '\t', 'L', '\v', '\t', '\x3', '\n', 
		'\x3', '\n', '\x3', '\n', '\a', '\n', 'Q', '\n', '\n', '\f', '\n', '\xE', 
		'\n', 'T', '\v', '\n', '\x5', '\n', 'V', '\n', '\n', '\x3', '\v', '\x3', 
		'\v', '\x3', '\v', '\x3', '\v', '\x5', '\v', '\\', '\n', '\v', '\x3', 
		'\v', '\x3', '\v', '\x5', '\v', '`', '\n', '\v', '\x3', '\v', '\x3', '\v', 
		'\x5', '\v', '\x64', '\n', '\v', '\x3', '\f', '\x3', '\f', '\x3', '\f', 
		'\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x5', '\f', 'm', 
		'\n', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', '\f', '\x3', 
		'\f', '\x3', '\f', '\x3', '\f', '\x5', '\f', 'v', '\n', '\f', '\x3', '\r', 
		'\x3', '\r', '\x3', '\r', '\x3', '\r', '\a', '\r', '|', '\n', '\r', '\f', 
		'\r', '\xE', '\r', '\x7F', '\v', '\r', '\x3', '\r', '\x3', '\r', '\x5', 
		'\r', '\x83', '\n', '\r', '\x3', '\r', '\x3', '\r', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\a', '\xE', '\x8B', '\n', '\xE', '\f', 
		'\xE', '\xE', '\xE', '\x8E', '\v', '\xE', '\x3', '\xE', '\x3', '\xE', 
		'\a', '\xE', '\x92', '\n', '\xE', '\f', '\xE', '\xE', '\xE', '\x95', '\v', 
		'\xE', '\x3', '\xE', '\a', '\xE', '\x98', '\n', '\xE', '\f', '\xE', '\xE', 
		'\xE', '\x9B', '\v', '\xE', '\x5', '\xE', '\x9D', '\n', '\xE', '\x3', 
		'\xE', '\a', '\xE', '\xA0', '\n', '\xE', '\f', '\xE', '\xE', '\xE', '\xA3', 
		'\v', '\xE', '\x3', '\xE', '\a', '\xE', '\xA6', '\n', '\xE', '\f', '\xE', 
		'\xE', '\xE', '\xA9', '\v', '\xE', '\x3', '\xE', '\x3', '\xE', '\x3', 
		'\xE', '\x3', '\xE', '\x3', '\xE', '\x3', '\xF', '\x3', '\xF', '\x6', 
		'\xF', '\xB2', '\n', '\xF', '\r', '\xF', '\xE', '\xF', '\xB3', '\x3', 
		'\xF', '\x3', '\xF', '\x6', '}', '\x8C', '\xA1', '\xA7', '\x2', '\x10', 
		'\x3', '\x2', '\x5', '\x2', '\a', '\x2', '\t', '\x2', '\v', '\x2', '\r', 
		'\x3', '\xF', '\x4', '\x11', '\x5', '\x13', '\x6', '\x15', '\a', '\x17', 
		'\b', '\x19', '\t', '\x1B', '\n', '\x1D', '\v', '\x3', '\x2', '\n', '\x3', 
		'\x2', '\x32', ';', '\x4', '\x2', '\x43', '\\', '\x63', '|', '\x4', '\x2', 
		'\f', '\f', '\xF', '\xF', '\x3', '\x2', '\x33', ';', '\x4', '\x2', 'G', 
		'G', 'g', 'g', '\a', '\x2', ')', ')', '^', '^', 'p', 'p', 't', 't', 'v', 
		'v', '\x4', '\x2', ',', ',', '\x31', '\x31', '\x4', '\x2', '\v', '\v', 
		'\"', '\"', '\x2', '\xCD', '\x2', '\r', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\xF', '\x3', '\x2', '\x2', '\x2', '\x2', '\x11', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x13', '\x3', '\x2', '\x2', '\x2', '\x2', '\x15', '\x3', 
		'\x2', '\x2', '\x2', '\x2', '\x17', '\x3', '\x2', '\x2', '\x2', '\x2', 
		'\x19', '\x3', '\x2', '\x2', '\x2', '\x2', '\x1B', '\x3', '\x2', '\x2', 
		'\x2', '\x2', '\x1D', '\x3', '\x2', '\x2', '\x2', '\x3', '\x1F', '\x3', 
		'\x2', '\x2', '\x2', '\x5', '!', '\x3', '\x2', '\x2', '\x2', '\a', '\x34', 
		'\x3', '\x2', '\x2', '\x2', '\t', '\x36', '\x3', '\x2', '\x2', '\x2', 
		'\v', ';', '\x3', '\x2', '\x2', '\x2', '\r', '=', '\x3', '\x2', '\x2', 
		'\x2', '\xF', '?', '\x3', '\x2', '\x2', '\x2', '\x11', '\x43', '\x3', 
		'\x2', '\x2', '\x2', '\x13', 'U', '\x3', '\x2', '\x2', '\x2', '\x15', 
		'\x63', '\x3', '\x2', '\x2', '\x2', '\x17', 'u', '\x3', '\x2', '\x2', 
		'\x2', '\x19', 'w', '\x3', '\x2', '\x2', '\x2', '\x1B', '\x86', '\x3', 
		'\x2', '\x2', '\x2', '\x1D', '\xB1', '\x3', '\x2', '\x2', '\x2', '\x1F', 
		' ', '\t', '\x2', '\x2', '\x2', ' ', '\x4', '\x3', '\x2', '\x2', '\x2', 
		'!', '\"', '\t', '\x3', '\x2', '\x2', '\"', '\x6', '\x3', '\x2', '\x2', 
		'\x2', '#', '%', '\x5', '\x13', '\n', '\x2', '$', '#', '\x3', '\x2', '\x2', 
		'\x2', '$', '%', '\x3', '\x2', '\x2', '\x2', '%', '&', '\x3', '\x2', '\x2', 
		'\x2', '&', '(', '\a', '\x30', '\x2', '\x2', '\'', ')', '\x5', '\x3', 
		'\x2', '\x2', '(', '\'', '\x3', '\x2', '\x2', '\x2', ')', '*', '\x3', 
		'\x2', '\x2', '\x2', '*', '(', '\x3', '\x2', '\x2', '\x2', '*', '+', '\x3', 
		'\x2', '\x2', '\x2', '+', '\x35', '\x3', '\x2', '\x2', '\x2', ',', '-', 
		'\x5', '\x13', '\n', '\x2', '-', '\x31', '\a', '\x30', '\x2', '\x2', '.', 
		'\x30', '\x5', '\x3', '\x2', '\x2', '/', '.', '\x3', '\x2', '\x2', '\x2', 
		'\x30', '\x33', '\x3', '\x2', '\x2', '\x2', '\x31', '/', '\x3', '\x2', 
		'\x2', '\x2', '\x31', '\x32', '\x3', '\x2', '\x2', '\x2', '\x32', '\x35', 
		'\x3', '\x2', '\x2', '\x2', '\x33', '\x31', '\x3', '\x2', '\x2', '\x2', 
		'\x34', '$', '\x3', '\x2', '\x2', '\x2', '\x34', ',', '\x3', '\x2', '\x2', 
		'\x2', '\x35', '\b', '\x3', '\x2', '\x2', '\x2', '\x36', '\x37', '\a', 
		'%', '\x2', '\x2', '\x37', '\n', '\x3', '\x2', '\x2', '\x2', '\x38', '<', 
		'\t', '\x4', '\x2', '\x2', '\x39', ':', '\a', '\xF', '\x2', '\x2', ':', 
		'<', '\a', '\f', '\x2', '\x2', ';', '\x38', '\x3', '\x2', '\x2', '\x2', 
		';', '\x39', '\x3', '\x2', '\x2', '\x2', '<', '\f', '\x3', '\x2', '\x2', 
		'\x2', '=', '>', '\a', ']', '\x2', '\x2', '>', '\xE', '\x3', '\x2', '\x2', 
		'\x2', '?', '@', '\a', '_', '\x2', '\x2', '@', '\x10', '\x3', '\x2', '\x2', 
		'\x2', '\x41', '\x44', '\a', '\x61', '\x2', '\x2', '\x42', '\x44', '\x5', 
		'\x5', '\x3', '\x2', '\x43', '\x41', '\x3', '\x2', '\x2', '\x2', '\x43', 
		'\x42', '\x3', '\x2', '\x2', '\x2', '\x44', 'J', '\x3', '\x2', '\x2', 
		'\x2', '\x45', 'I', '\a', '\x61', '\x2', '\x2', '\x46', 'I', '\x5', '\x3', 
		'\x2', '\x2', 'G', 'I', '\x5', '\x5', '\x3', '\x2', 'H', '\x45', '\x3', 
		'\x2', '\x2', '\x2', 'H', '\x46', '\x3', '\x2', '\x2', '\x2', 'H', 'G', 
		'\x3', '\x2', '\x2', '\x2', 'I', 'L', '\x3', '\x2', '\x2', '\x2', 'J', 
		'H', '\x3', '\x2', '\x2', '\x2', 'J', 'K', '\x3', '\x2', '\x2', '\x2', 
		'K', '\x12', '\x3', '\x2', '\x2', '\x2', 'L', 'J', '\x3', '\x2', '\x2', 
		'\x2', 'M', 'V', '\a', '\x32', '\x2', '\x2', 'N', 'R', '\t', '\x5', '\x2', 
		'\x2', 'O', 'Q', '\t', '\x2', '\x2', '\x2', 'P', 'O', '\x3', '\x2', '\x2', 
		'\x2', 'Q', 'T', '\x3', '\x2', '\x2', '\x2', 'R', 'P', '\x3', '\x2', '\x2', 
		'\x2', 'R', 'S', '\x3', '\x2', '\x2', '\x2', 'S', 'V', '\x3', '\x2', '\x2', 
		'\x2', 'T', 'R', '\x3', '\x2', '\x2', '\x2', 'U', 'M', '\x3', '\x2', '\x2', 
		'\x2', 'U', 'N', '\x3', '\x2', '\x2', '\x2', 'V', '\x14', '\x3', '\x2', 
		'\x2', '\x2', 'W', '\x64', '\x5', '\a', '\x4', '\x2', 'X', '\x64', '\x5', 
		'\x13', '\n', '\x2', 'Y', '\\', '\x5', '\a', '\x4', '\x2', 'Z', '\\', 
		'\x5', '\x13', '\n', '\x2', '[', 'Y', '\x3', '\x2', '\x2', '\x2', '[', 
		'Z', '\x3', '\x2', '\x2', '\x2', '\\', ']', '\x3', '\x2', '\x2', '\x2', 
		']', '_', '\t', '\x6', '\x2', '\x2', '^', '`', '\a', '/', '\x2', '\x2', 
		'_', '^', '\x3', '\x2', '\x2', '\x2', '_', '`', '\x3', '\x2', '\x2', '\x2', 
		'`', '\x61', '\x3', '\x2', '\x2', '\x2', '\x61', '\x62', '\x5', '\x13', 
		'\n', '\x2', '\x62', '\x64', '\x3', '\x2', '\x2', '\x2', '\x63', 'W', 
		'\x3', '\x2', '\x2', '\x2', '\x63', 'X', '\x3', '\x2', '\x2', '\x2', '\x63', 
		'[', '\x3', '\x2', '\x2', '\x2', '\x64', '\x16', '\x3', '\x2', '\x2', 
		'\x2', '\x65', '\x66', '\a', ')', '\x2', '\x2', '\x66', 'g', '\v', '\x2', 
		'\x2', '\x2', 'g', 'v', '\a', ')', '\x2', '\x2', 'h', 'i', '\a', ')', 
		'\x2', '\x2', 'i', 'j', '\a', '^', '\x2', '\x2', 'j', 'l', '\x3', '\x2', 
		'\x2', '\x2', 'k', 'm', '\t', '\a', '\x2', '\x2', 'l', 'k', '\x3', '\x2', 
		'\x2', '\x2', 'm', 'n', '\x3', '\x2', '\x2', '\x2', 'n', 'v', '\a', ')', 
		'\x2', '\x2', 'o', 'p', '\a', ')', '\x2', '\x2', 'p', 'q', '\a', '^', 
		'\x2', '\x2', 'q', 'r', '\x3', '\x2', '\x2', '\x2', 'r', 's', '\x5', '\x13', 
		'\n', '\x2', 's', 't', '\a', ')', '\x2', '\x2', 't', 'v', '\x3', '\x2', 
		'\x2', '\x2', 'u', '\x65', '\x3', '\x2', '\x2', '\x2', 'u', 'h', '\x3', 
		'\x2', '\x2', '\x2', 'u', 'o', '\x3', '\x2', '\x2', '\x2', 'v', '\x18', 
		'\x3', '\x2', '\x2', '\x2', 'w', 'x', '\a', '\x31', '\x2', '\x2', 'x', 
		'y', '\a', '\x31', '\x2', '\x2', 'y', '}', '\x3', '\x2', '\x2', '\x2', 
		'z', '|', '\v', '\x2', '\x2', '\x2', '{', 'z', '\x3', '\x2', '\x2', '\x2', 
		'|', '\x7F', '\x3', '\x2', '\x2', '\x2', '}', '~', '\x3', '\x2', '\x2', 
		'\x2', '}', '{', '\x3', '\x2', '\x2', '\x2', '~', '\x82', '\x3', '\x2', 
		'\x2', '\x2', '\x7F', '}', '\x3', '\x2', '\x2', '\x2', '\x80', '\x83', 
		'\x5', '\v', '\x6', '\x2', '\x81', '\x83', '\a', '\x2', '\x2', '\x3', 
		'\x82', '\x80', '\x3', '\x2', '\x2', '\x2', '\x82', '\x81', '\x3', '\x2', 
		'\x2', '\x2', '\x83', '\x84', '\x3', '\x2', '\x2', '\x2', '\x84', '\x85', 
		'\b', '\r', '\x2', '\x2', '\x85', '\x1A', '\x3', '\x2', '\x2', '\x2', 
		'\x86', '\x87', '\a', '\x31', '\x2', '\x2', '\x87', '\x88', '\a', ',', 
		'\x2', '\x2', '\x88', '\xA1', '\x3', '\x2', '\x2', '\x2', '\x89', '\x8B', 
		'\a', '\x31', '\x2', '\x2', '\x8A', '\x89', '\x3', '\x2', '\x2', '\x2', 
		'\x8B', '\x8E', '\x3', '\x2', '\x2', '\x2', '\x8C', '\x8D', '\x3', '\x2', 
		'\x2', '\x2', '\x8C', '\x8A', '\x3', '\x2', '\x2', '\x2', '\x8D', '\x8F', 
		'\x3', '\x2', '\x2', '\x2', '\x8E', '\x8C', '\x3', '\x2', '\x2', '\x2', 
		'\x8F', '\xA0', '\x5', '\x1B', '\xE', '\x2', '\x90', '\x92', '\a', '\x31', 
		'\x2', '\x2', '\x91', '\x90', '\x3', '\x2', '\x2', '\x2', '\x92', '\x95', 
		'\x3', '\x2', '\x2', '\x2', '\x93', '\x91', '\x3', '\x2', '\x2', '\x2', 
		'\x93', '\x94', '\x3', '\x2', '\x2', '\x2', '\x94', '\x9D', '\x3', '\x2', 
		'\x2', '\x2', '\x95', '\x93', '\x3', '\x2', '\x2', '\x2', '\x96', '\x98', 
		'\a', ',', '\x2', '\x2', '\x97', '\x96', '\x3', '\x2', '\x2', '\x2', '\x98', 
		'\x9B', '\x3', '\x2', '\x2', '\x2', '\x99', '\x97', '\x3', '\x2', '\x2', 
		'\x2', '\x99', '\x9A', '\x3', '\x2', '\x2', '\x2', '\x9A', '\x9D', '\x3', 
		'\x2', '\x2', '\x2', '\x9B', '\x99', '\x3', '\x2', '\x2', '\x2', '\x9C', 
		'\x93', '\x3', '\x2', '\x2', '\x2', '\x9C', '\x99', '\x3', '\x2', '\x2', 
		'\x2', '\x9D', '\x9E', '\x3', '\x2', '\x2', '\x2', '\x9E', '\xA0', '\n', 
		'\b', '\x2', '\x2', '\x9F', '\x8C', '\x3', '\x2', '\x2', '\x2', '\x9F', 
		'\x9C', '\x3', '\x2', '\x2', '\x2', '\xA0', '\xA3', '\x3', '\x2', '\x2', 
		'\x2', '\xA1', '\xA2', '\x3', '\x2', '\x2', '\x2', '\xA1', '\x9F', '\x3', 
		'\x2', '\x2', '\x2', '\xA2', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xA3', 
		'\xA1', '\x3', '\x2', '\x2', '\x2', '\xA4', '\xA6', '\a', ',', '\x2', 
		'\x2', '\xA5', '\xA4', '\x3', '\x2', '\x2', '\x2', '\xA6', '\xA9', '\x3', 
		'\x2', '\x2', '\x2', '\xA7', '\xA8', '\x3', '\x2', '\x2', '\x2', '\xA7', 
		'\xA5', '\x3', '\x2', '\x2', '\x2', '\xA8', '\xAA', '\x3', '\x2', '\x2', 
		'\x2', '\xA9', '\xA7', '\x3', '\x2', '\x2', '\x2', '\xAA', '\xAB', '\a', 
		',', '\x2', '\x2', '\xAB', '\xAC', '\a', '\x31', '\x2', '\x2', '\xAC', 
		'\xAD', '\x3', '\x2', '\x2', '\x2', '\xAD', '\xAE', '\b', '\xE', '\x2', 
		'\x2', '\xAE', '\x1C', '\x3', '\x2', '\x2', '\x2', '\xAF', '\xB2', '\t', 
		'\t', '\x2', '\x2', '\xB0', '\xB2', '\x5', '\v', '\x6', '\x2', '\xB1', 
		'\xAF', '\x3', '\x2', '\x2', '\x2', '\xB1', '\xB0', '\x3', '\x2', '\x2', 
		'\x2', '\xB2', '\xB3', '\x3', '\x2', '\x2', '\x2', '\xB3', '\xB1', '\x3', 
		'\x2', '\x2', '\x2', '\xB3', '\xB4', '\x3', '\x2', '\x2', '\x2', '\xB4', 
		'\xB5', '\x3', '\x2', '\x2', '\x2', '\xB5', '\xB6', '\b', '\xF', '\x2', 
		'\x2', '\xB6', '\x1E', '\x3', '\x2', '\x2', '\x2', '\x1D', '\x2', '$', 
		'*', '\x31', '\x34', ';', '\x43', 'H', 'J', 'R', 'U', '[', '_', '\x63', 
		'l', 'u', '}', '\x82', '\x8C', '\x93', '\x99', '\x9C', '\x9F', '\xA1', 
		'\xA7', '\xB1', '\xB3', '\x3', '\b', '\x2', '\x2',
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
